#!/usr/bin/env python3
from flask_jwt_extended import decode_token

token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc0MzA2NjE2MywianRpIjoiMWIxYTllN2YtNjUwMi00YWQ0LWI3ZWMtMGU2YWM3NmM5Y2NiIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjciLCJuYmYiOjE3NDMwNjYxNjMsImNzcmYiOiI0ZTA5NGU1Mi1lOTk2LTQ3ZWItOTM2Ni1jYTU3NmNiNWRlODAiLCJleHAiOjE3NDMwOTg1NjMsInJvbGUiOiJtZW1iZXIiLCJlbWFpbCI6Im1hcnlAZ21haWwuY29tIn0.d_hnzvF9hvJ6ZavUcWkB4tBqN6iq3btYPvKtcaIXFC8"
decoded = decode_token(token)
print(decoded)
