"""Add borrow_date to Borrow

Revision ID: 16511852f669
Revises: e910a4f61014
Create Date: 2025-03-27 15:58:25.090932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '16511852f669'
down_revision = 'e910a4f61014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrow_date', sa.DateTime(), nullable=False))
        batch_op.drop_column('borrowed_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrowed_date', mysql.DATETIME(), nullable=False))
        batch_op.drop_column('borrow_date')

    # ### end Alembic commands ###
